# Auto-generated by gen_config.py — do not edit.
TACVAR_ARCH := aarch64
TACVAR_CONSUMER := npb-mpi
TACVAR_TIMER := native
TACVAR_TIMER_RESOLVED := mpi_wtime
TACVAR_COUNTER_BACKEND := none
TACVAR_MEASURE_OBJS := tacvar_measure.o tacvar_csv.o
TACVAR_MEASURE_CFLAGS := -I/mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure -I/mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure/include -I/mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure/timers -I/mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure/counters -I/mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure/events -DTACVAR_HAS_GENERATED_CONFIG=1
TACVAR_MEASURE_LDFLAGS := 
TACVAR_MEASURE_ROOT := /mnt/keylabmain/nfs/hpckey/03-Project/TacVar_NPC/src/measure
