#!/usr/bin/env bash
# NPB-MPI Class C timer×counter campaign on c920bn1 (aarch64).
# Preflight gates 4 PAPI events (non-zero deltas), then runs:
#   timers × {e0,e4} × {BT,CG,EP,FT,IS,LU,MG,SP}
# Archives conf/cmd/stdout/data under results_c920bn1_classC_<ts>/.
# Resumable: skips runs that already have STATUS=PASS.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
MPI_DIR="$ROOT/NPB3.4-MPI"
ARCH=$(uname -m)

if [[ "$ARCH" != "aarch64" ]]; then
  echo "ERROR: this campaign targets aarch64 (c920bn1); got $ARCH" >&2
  exit 2
fi

export MPI_HOME="${MPI_HOME:-/home/hpckey/01-App/openmpi-5.0.8}"
export PAPI_HOME="${PAPI_HOME:-/home/hpckey/01-App/papi}"
export PATH="${MPI_HOME}/bin:${PATH}"
export LD_LIBRARY_PATH="${MPI_HOME}/lib:${PAPI_HOME}/lib:${LD_LIBRARY_PATH:-}"

# CNTVCT ns/tick (HiSilicon often 100 MHz → 10)
frq=$(awk '/CNTFRQ|cntfrq/ {print $3; exit}' /proc/cpuinfo 2>/dev/null || true)
if [[ -z "${frq:-}" ]]; then
  frq=100000000
fi
if [[ "$frq" =~ ^[0-9]+$ ]] && [[ "$frq" -gt 0 ]]; then
  NSTP=$(( (1000000000 + frq/2) / frq ))
else
  NSTP=10
fi

TIMERS=(native clock_gettime papi_get_real_nsec cntvct_el0 cntvct_el0_dmb)
APPS=(BT CG EP FT IS LU MG SP)
# Default 4-event set; may be rewritten after preflight substitutions.
EVENTS4_DEFAULT="PAPI_TOT_CYC,PAPI_TOT_INS,PAPI_L1_DCM,PAPI_LST_INS"
EVENTS4_FALLBACKS=(
  "PAPI_TOT_CYC,PAPI_TOT_INS,PAPI_L1_DCM,PAPI_LST_INS"
  "PAPI_TOT_CYC,PAPI_TOT_INS,PAPI_L1_DCM,PAPI_LD_INS"
  "PAPI_TOT_CYC,PAPI_TOT_INS,PAPI_BR_INS,PAPI_LD_INS"
  "PAPI_TOT_CYC,PAPI_TOT_INS,PAPI_L1_DCA,PAPI_LST_INS"
)

NP_DEFAULT=128
NP_SQUARE=121   # BT/SP require square process count
MAP_BIND=(--map-by core --bind-to core)

# Results root: reuse if RESUME_DIR set, else create timestamped.
if [[ -n "${RESUME_DIR:-}" ]]; then
  RESULTS="$RESUME_DIR"
  [[ -d "$RESULTS" ]] || { echo "ERROR: RESUME_DIR=$RESULTS missing" >&2; exit 2; }
else
  TS=$(date +%Y%m%dT%H%M%S)
  RESULTS="$MPI_DIR/results_c920bn1_classC_${TS}"
  mkdir -p "$RESULTS"/{preflight,runs,summary}
fi
LOG="$RESULTS/campaign.log"
EVENTS4_FILE="$RESULTS/events4.txt"
STATUS_CSV="$RESULTS/run_status.csv"

log() { echo "[$(date +%H:%M:%S)] $*" | tee -a "$LOG"; }

write_meta() {
  cat > "$RESULTS/meta.env" <<EOF
HOST=$(hostname)
ARCH=$ARCH
NPROC=$(nproc)
DATE=$(date -Iseconds)
MPI_HOME=$MPI_HOME
PAPI_HOME=$PAPI_HOME
MPI_VERSION=$("$MPI_HOME/bin/mpirun" --version 2>&1 | head -1)
PAPI_VERSION=$("$PAPI_HOME/bin/papi_version" 2>/dev/null || echo unknown)
CNTFRQ_ASSUMED=$frq
TACVAR_NSTP=$NSTP
NP_DEFAULT=$NP_DEFAULT
NP_SQUARE=$NP_SQUARE
CLASS=C
APPS=${APPS[*]}
TIMERS=${TIMERS[*]}
EOF
}

# Backup original conf once; restore on exit.
ORIG_CONF_BAK="$RESULTS/tacvar.conf.orig"
if [[ ! -f "$ORIG_CONF_BAK" ]]; then
  cp "$MPI_DIR/tacvar.conf" "$ORIG_CONF_BAK"
fi

restore_conf() {
  if [[ -f "$ORIG_CONF_BAK" ]]; then
    cp -f "$ORIG_CONF_BAK" "$MPI_DIR/tacvar.conf"
    touch "$MPI_DIR/tacvar.conf"
  fi
}
trap 'restore_conf' EXIT

apply_conf() {
  local timer="$1" counter="$2" names="$3" count="$4" nstp="$5"
  cat > "$MPI_DIR/tacvar.conf" <<EOF
# Generated by run_npb_timer_classC_c920.sh — do not edit mid-run
TACVAR_TIMER=$timer
TACVAR_NSTP=$nstp
TACVAR_COUNTER_BACKEND=$counter
TACVAR_COUNTER_COUNT=$count
TACVAR_COUNTER_NAMES=$names
TACVAR_OUTPUT_ROOT=.
TACVAR_ENABLE_PER_STEP_TIMING=1
EOF
}

force_rebuild() {
  local arch
  arch=$(uname -m)
  rm -rf "$MPI_DIR/config/tacvar_build" "$MPI_DIR/config/tacvar_build_${arch}"
  rm -f "$MPI_DIR/common/"*.o "$MPI_DIR/sys/setparams" "$MPI_DIR/bin/"*.x
  find "$MPI_DIR" -mindepth 2 -maxdepth 2 -type f -name '*.o' -delete 2>/dev/null || true
}

nstp_for_timer() {
  local t="$1"
  case "$t" in
    cntvct_el0|cntvct_el0_dmb) echo "$NSTP" ;;
    *) echo 0 ;;
  esac
}

np_for_app() {
  local app="$1"
  case "$app" in
    BT|SP) echo "$NP_SQUARE" ;;
    *) echo "$NP_DEFAULT" ;;
  esac
}

combo_tag() {
  local timer="$1" count="$2"
  if [[ "$count" -eq 0 ]]; then
    echo "${timer}_e0"
  else
    echo "${timer}_e4"
  fi
}

run_dir() {
  local tag="$1" app="$2"
  echo "$RESULTS/runs/${tag}/$(echo "$app" | tr '[:upper:]' '[:lower:]')"
}

already_pass() {
  local dir="$1"
  [[ -f "$dir/STATUS" ]] && grep -qx 'PASS' "$dir/STATUS"
}

is_skip_output() {
  local out="$1"
  grep -qiE 'Permission denied|Operation not permitted|not supported|PAPI_.*disabled|Component .* disabled|cannot open ph_enable_pmu|Event does not exist|Event.*not available|EPERM|ENOTSUP|perf_event_open failed|Failed to open|No such device|kmod|PAPI Error|papi.*fail' "$out" 2>/dev/null
}

# Check each named *_delta column has at least one non-zero across all CSVs in dir.
check_nonzero_events() {
  local data_dir="$1"
  shift
  local names=("$@")
  local name csv col found
  python3 - "$data_dir" "${names[@]}" <<'PY'
import csv, glob, sys
data_dir = sys.argv[1]
names = sys.argv[2:]
files = sorted(glob.glob(data_dir + "/npb-mpi_*.csv"))
if not files:
    print("NO_CSV")
    sys.exit(2)
missing = []
for name in names:
    col = name + "_delta"
    ok = False
    for path in files:
        with open(path, newline="") as f:
            r = csv.DictReader(f)
            if col not in (r.fieldnames or []):
                continue
            for row in r:
                try:
                    if int(row[col]) != 0:
                        ok = True
                        break
                except (ValueError, TypeError):
                    pass
        if ok:
            break
    if not ok:
        missing.append(name)
if missing:
    print("ZERO:" + ",".join(missing))
    sys.exit(1)
print("OK")
sys.exit(0)
PY
}

archive_run() {
  local dest="$1" out="$2" status="$3"
  mkdir -p "$dest"
  cp -f "$MPI_DIR/tacvar.conf" "$dest/tacvar.conf"
  # Move newest data_* into dest
  local data
  data=$(ls -dt "$MPI_DIR"/data_????????T?????? 2>/dev/null | head -1 || true)
  if [[ -n "$data" ]]; then
    # Avoid clobbering on resume re-run
    local base
    base=$(basename "$data")
    if [[ -d "$dest/$base" ]]; then
      rm -rf "$dest/$base"
    fi
    mv "$data" "$dest/"
  fi
  cp -f "$out" "$dest/stdout.log"
  echo "$status" > "$dest/STATUS"
}

write_cmd_sh() {
  local dest="$1" app="$2" np="$3" bin="$4"
  cat > "$dest/cmd.sh" <<EOF
#!/usr/bin/env bash
# Saved run command for afterwards analysis
set -euo pipefail
export PATH=$MPI_HOME/bin:\$PATH
export LD_LIBRARY_PATH=$MPI_HOME/lib:$PAPI_HOME/lib:\${LD_LIBRARY_PATH:-}
export MPI_HOME=$MPI_HOME
export PAPI_HOME=$PAPI_HOME
export NPB_TIMER_FLAG=1
cd $(printf '%q' "$MPI_DIR")
mpirun -np $np ${MAP_BIND[*]} ./bin/$bin
EOF
  chmod +x "$dest/cmd.sh"
}

append_status() {
  local tag="$1" app="$2" status="$3" note="$4"
  if [[ ! -f "$STATUS_CSV" ]]; then
    echo "tag,app,status,note,ts" > "$STATUS_CSV"
  fi
  echo "${tag},${app},${status},${note},$(date -Iseconds)" >> "$STATUS_CSV"
}

# ---------- preflight ----------
run_preflight_e0() {
  local dest="$RESULTS/preflight/e0_none"
  if already_pass "$dest"; then
    log "SKIP preflight e0 (already PASS)"
    return 0
  fi
  mkdir -p "$dest"
  log "=== preflight e0 (none) ==="
  apply_conf clock_gettime none "" 0 0
  force_rebuild
  local out="$dest/build_run.out"
  set +e
  (cd "$MPI_DIR" && make MG CLASS=S) >"$out" 2>&1
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    set -e
    echo FAIL > "$dest/STATUS"
    log "FAIL preflight e0 compile"
    return 1
  fi
  rm -rf "$MPI_DIR"/data_????????T??????
  export NPB_TIMER_FLAG=1
  (cd "$MPI_DIR" && mpirun -np 4 "${MAP_BIND[@]}" ./bin/mg.S.x) >>"$out" 2>&1
  rc=$?
  set -e
  write_cmd_sh "$dest" MG 4 mg.S.x
  cp -f "$MPI_DIR/tacvar.conf" "$dest/tacvar.conf"
  local data data_path csv0
  data=$(ls -dt "$MPI_DIR"/data_????????T?????? 2>/dev/null | head -1 || true)
  [[ -n "$data" ]] && mv "$data" "$dest/"
  cp -f "$out" "$dest/stdout.log"
  data_path=$(ls -dt "$dest"/data_????????T?????? 2>/dev/null | head -1 || true)
  csv0=$(ls "$data_path"/npb-mpi_*.csv 2>/dev/null | head -1 || true)
  if grep -q SUCCESSFUL "$out" && [[ -n "$data_path" ]] && [[ -f "$data_path/region_info.csv" ]] && [[ -n "$csv0" ]]; then
    # Schema check: no counter_backend column
    if head -1 "$csv0" | grep -q counter_backend; then
      echo FAIL > "$dest/STATUS"
      log "FAIL preflight e0 unexpected counter columns"
      return 1
    fi
    echo PASS > "$dest/STATUS"
    log "PASS preflight e0"
    return 0
  fi
  echo FAIL > "$dest/STATUS"
  log "FAIL preflight e0 (successful=$(grep -c SUCCESSFUL "$out" || true) data=$data_path csv=$csv0)"
  return 1
}

run_preflight_e4() {
  local names="$1"
  local dest="$RESULTS/preflight/e4_papi"
  mkdir -p "$dest"
  log "=== preflight e4 names=$names ==="
  apply_conf clock_gettime papi_read "$names" 4 0
  force_rebuild
  local out="$dest/build_run.out"
  set +e
  (cd "$MPI_DIR" && make MG CLASS=S) >"$out" 2>&1
  local rc=$?
  if [[ $rc -ne 0 ]]; then
    set -e
    echo FAIL > "$dest/STATUS"
    cp -f "$out" "$dest/stdout.log"
    log "FAIL preflight e4 compile"
    return 1
  fi
  rm -rf "$MPI_DIR"/data_????????T??????
  export NPB_TIMER_FLAG=1
  (cd "$MPI_DIR" && mpirun -np 4 "${MAP_BIND[@]}" ./bin/mg.S.x) >>"$out" 2>&1
  rc=$?
  set -e
  write_cmd_sh "$dest" MG 4 mg.S.x
  cp -f "$MPI_DIR/tacvar.conf" "$dest/tacvar.conf"
  # Remove prior data dirs in dest from previous attempts
  rm -rf "$dest"/data_????????T??????
  local data
  data=$(ls -dt "$MPI_DIR"/data_????????T?????? 2>/dev/null | head -1 || true)
  if [[ -z "$data" ]]; then
    cp -f "$out" "$dest/stdout.log"
    echo FAIL > "$dest/STATUS"
    log "FAIL preflight e4 no data dir"
    return 1
  fi
  mv "$data" "$dest/"
  cp -f "$out" "$dest/stdout.log"
  echo "$names" > "$dest/events4.txt"
  if ! grep -q SUCCESSFUL "$out"; then
    if is_skip_output "$out"; then
      echo SKIP > "$dest/STATUS"
      log "SKIP preflight e4 host limitation"
      return 2
    fi
    echo FAIL > "$dest/STATUS"
    log "FAIL preflight e4 verification"
    return 1
  fi
  local data_path
  data_path=$(ls -dt "$dest"/data_????????T?????? | head -1)
  IFS=',' read -r -a name_arr <<< "$names"
  set +e
  local chk
  chk=$(check_nonzero_events "$data_path" "${name_arr[@]}")
  local crc=$?
  set -e
  echo "$chk" > "$dest/nonzero_check.txt"
  if [[ $crc -ne 0 ]]; then
    echo FAIL > "$dest/STATUS"
    log "FAIL preflight e4 counters: $chk"
    return 1
  fi
  echo PASS > "$dest/STATUS"
  echo "$names" > "$EVENTS4_FILE"
  log "PASS preflight e4 ($names)"
  return 0
}

gate_events4() {
  if [[ -f "$EVENTS4_FILE" ]] && [[ -f "$RESULTS/preflight/e4_papi/STATUS" ]] \
     && grep -qx PASS "$RESULTS/preflight/e4_papi/STATUS"; then
    log "Using cached events4: $(cat "$EVENTS4_FILE")"
    return 0
  fi
  local names
  for names in "${EVENTS4_FALLBACKS[@]}"; do
    set +e
    run_preflight_e4 "$names"
    local rc=$?
    set -e
    if [[ $rc -eq 0 ]]; then
      return 0
    fi
    log "Trying next event set after failure for: $names"
  done
  log "ERROR: no 4-event set produced non-zero deltas"
  return 1
}

# ---------- formal matrix ----------
run_one() {
  local timer="$1" count="$2" names="$3" app="$4"
  local tag nstp np bin dest out rc
  tag=$(combo_tag "$timer" "$count")
  nstp=$(nstp_for_timer "$timer")
  np=$(np_for_app "$app")
  bin="$(echo "$app" | tr '[:upper:]' '[:lower:]').C.x"
  dest=$(run_dir "$tag" "$app")

  if already_pass "$dest"; then
    log "SKIP $tag/$app (already PASS)"
    return 0
  fi

  mkdir -p "$dest"
  log "=== $tag / $app (np=$np) ==="

  # Conf must match current timer×events; caller rebuilds when combo changes.
  # Ensure conf is current:
  if [[ "$count" -eq 0 ]]; then
    apply_conf "$timer" none "" 0 "$nstp"
  else
    apply_conf "$timer" papi_read "$names" 4 "$nstp"
  fi

  out="$dest/build_run.out"
  set +e
  (cd "$MPI_DIR" && make "$app" CLASS=C) >"$out" 2>&1
  rc=$?
  if [[ $rc -ne 0 ]]; then
    set -e
    if is_skip_output "$out"; then
      archive_run "$dest" "$out" SKIP
      write_cmd_sh "$dest" "$app" "$np" "$bin"
      append_status "$tag" "$app" SKIP "compile"
      log "SKIP $tag/$app compile host limitation"
      return 0
    fi
    archive_run "$dest" "$out" FAIL
    write_cmd_sh "$dest" "$app" "$np" "$bin"
    append_status "$tag" "$app" FAIL "compile"
    log "FAIL $tag/$app compile"
    return 0
  fi

  rm -rf "$MPI_DIR"/data_????????T??????
  export NPB_TIMER_FLAG=1
  (cd "$MPI_DIR" && mpirun -np "$np" "${MAP_BIND[@]}" "./bin/$bin") >>"$out" 2>&1
  rc=$?
  set -e

  write_cmd_sh "$dest" "$app" "$np" "$bin"

  if [[ $rc -ne 0 ]] && is_skip_output "$out"; then
    archive_run "$dest" "$out" SKIP
    append_status "$tag" "$app" SKIP "runtime"
    log "SKIP $tag/$app runtime host limitation"
    return 0
  fi
  if ! grep -q SUCCESSFUL "$out"; then
    if is_skip_output "$out"; then
      archive_run "$dest" "$out" SKIP
      append_status "$tag" "$app" SKIP "verify/host"
      log "SKIP $tag/$app verify/host"
      return 0
    fi
    archive_run "$dest" "$out" FAIL
    append_status "$tag" "$app" FAIL "verify"
    log "FAIL $tag/$app verification"
    return 0
  fi

  archive_run "$dest" "$out" PASS
  append_status "$tag" "$app" PASS "ok"
  log "PASS $tag/$app"
  return 0
}

run_matrix() {
  local events4
  events4=$(cat "$EVENTS4_FILE")
  local timer count names nstp tag
  for timer in "${TIMERS[@]}"; do
    for count in 0 4; do
      nstp=$(nstp_for_timer "$timer")
      tag=$(combo_tag "$timer" "$count")
      log "=== rebuild combo $tag ==="
      if [[ "$count" -eq 0 ]]; then
        names=""
        apply_conf "$timer" none "" 0 "$nstp"
      else
        names="$events4"
        apply_conf "$timer" papi_read "$names" 4 "$nstp"
      fi
      force_rebuild
      local app
      for app in "${APPS[@]}"; do
        run_one "$timer" "$count" "$names" "$app"
      done
    done
  done
}

# ---------- main ----------
mkdir -p "$RESULTS"/{preflight,runs,summary}
: >> "$LOG"
write_meta
log "Results: $RESULTS"
log "NSTP=$NSTP CNTFRQ=$frq"

PHASE="${1:-all}"

case "$PHASE" in
  preflight)
    run_preflight_e0
    gate_events4
    ;;
  matrix)
    [[ -f "$EVENTS4_FILE" ]] || { log "ERROR: run preflight first"; exit 2; }
    run_matrix
    ;;
  all)
    run_preflight_e0
    gate_events4
    run_matrix
    log "Campaign matrix complete. Run summarize next."
    echo "$RESULTS" > "$RESULTS/RESULTS_PATH.txt"
    echo "$RESULTS"
    ;;
  *)
    echo "Usage: $0 [all|preflight|matrix]" >&2
    exit 2
    ;;
esac
