#!/usr/bin/env python3
"""
@file gen_tf_nsamp.py
@brief Build tacvar_tf_nsamp.h from median.csv (ngauge) and nspg.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Optional


NGAUGE_MIN = 10


def load_nspg(nspg_arg: str, nspg_file: Path | None) -> float:
    if nspg_arg and float(nspg_arg) > 0:
        return float(nspg_arg)
    if nspg_file and nspg_file.is_file():
        text = nspg_file.read_text().strip().splitlines()
        if not text:
            raise SystemExit(f"empty nspg file: {nspg_file}")
        return float(text[0].split()[0])
    raise SystemExit("need --nspg > 0 or an nspg.txt file")


def read_median(path: Path) -> list[tuple[str, str, int, int, float, Optional[int]]]:
    rows: list[tuple[str, str, int, int, float, Optional[int]]] = []
    with path.open(newline="") as fp:
        reader = csv.DictReader(fp)
        if not reader.fieldnames:
            raise SystemExit(f"empty median.csv: {path}")
        fields = {n.lower(): n for n in reader.fieldnames}
        for key in ("kernel", "class", "region_id", "median"):
            if key not in fields:
                raise SystemExit(f"median.csv missing column {key}")
        loc_key = fields.get("loc_id") or fields.get("log_id")
        if not loc_key:
            raise SystemExit("median.csv missing loc_id")
        ngauge_key = fields.get("ngauge")
        for rec in reader:
            kernel = rec[fields["kernel"]].strip()
            klass = rec[fields["class"]].strip()
            rid = int(float(rec[fields["region_id"]]))
            loc = int(float(rec[loc_key]))
            med = float(rec[fields["median"]])
            ngauge: Optional[int] = None
            if ngauge_key:
                raw = rec.get(ngauge_key, "").strip()
                if raw:
                    ngauge = int(float(raw))
            rows.append((kernel, klass, rid, loc, med, ngauge))
    if not rows:
        raise SystemExit(f"no data rows in {path}")
    return rows


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--median", required=True, help="median.csv from get_median.py")
    ap.add_argument("--nspg", default="0", help="ns per gauge step (overrides file)")
    ap.add_argument("--nspg-file", default="", help="path to nspg.txt")
    ap.add_argument("--out-h", required=True, help="tacvar_tf_nsamp.h")
    ap.add_argument("--kernel", default="", help="optional kernel filter (CG)")
    ap.add_argument("--klass", default="", help="optional class filter (C)")
    args = ap.parse_args()

    median_path = Path(args.median)
    if not median_path.is_file():
        raise SystemExit(f"median.csv not found: {median_path}")

    nspg_file = Path(args.nspg_file) if args.nspg_file else median_path.parent / "nspg.txt"
    nspg = load_nspg(args.nspg, nspg_file)
    if nspg <= 0:
        raise SystemExit(f"nspg must be > 0, got {nspg}")

    rows = read_median(median_path)
    kfilt = args.kernel.strip().upper()
    cfilt = args.klass.strip().upper()
    table: list[tuple[int, int, int]] = []
    for kernel, klass, rid, loc, med, ngauge in rows:
        if kfilt and kernel.upper() != kfilt:
            continue
        if cfilt and klass.upper() != cfilt:
            continue
        if ngauge is not None and ngauge > 0:
            n = ngauge
        else:
            n = int(med / nspg)
            if n < NGAUGE_MIN:
                n = NGAUGE_MIN
        table.append((rid, loc, n))

    if not table:
        raise SystemExit("no median rows matched kernel/class filter")

    lines = [
        "/* Auto-generated by gen_tf_nsamp.py — do not edit. */",
        "#ifndef TACVAR_TF_NSAMP_H_INCLUDED",
        "#define TACVAR_TF_NSAMP_H_INCLUDED",
        "",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        f"#define TACVAR_TF_NSAMP_COUNT {len(table)}",
        f"#define TACVAR_TF_NSAMP_NSPG {nspg}",
        "",
        "static const struct {",
        "    int region_id;",
        "    int loc_id;",
        "    uint64_t ngauge;",
        "} TACVAR_TF_NSAMP_TABLE[TACVAR_TF_NSAMP_COUNT] = {",
    ]
    for rid, loc, n in table:
        lines.append(f"    {{ {rid}, {loc}, {n}ULL }},")
    lines += [
        "};",
        "",
        "#endif /* TACVAR_TF_NSAMP_H_INCLUDED */",
        "",
    ]
    out_h = Path(args.out_h)
    out_h.parent.mkdir(parents=True, exist_ok=True)
    out_h.write_text("\n".join(lines))
    print(f"wrote {out_h} ({len(table)} sites, nspg={nspg})")


if __name__ == "__main__":
    main()
